[grok]
key = "xai-UdBZ4Pa96KV34g2S988FSZoWkn4jESkILZ9AORNBvRQslvtsaep7AIeEQKENkz46rC7ugvr38MMfQn6H"

[alpha_vantage]
key = "XV8DT58Z4VPIS7X5"

[general]
app_name = "ShipTrack + GeoSupply Hybrid"
version = "V2.0"
